"""add fighter name split, fight name, profile picture

Revision ID: 035991809617
Revises: 4b8202cc1d0c
Create Date: 2026-08-07 01:42:00.541242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035991809617'
down_revision: Union[str, Sequence[str], None] = '4b8202cc1d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighter_profiles', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('fighter_profiles', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('fighter_profiles', sa.Column('fight_name', sa.String(length=120), nullable=True))
    op.add_column('fighter_profiles', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.drop_column('fighter_profiles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighter_profiles', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('fighter_profiles', 'profile_picture_url')
    op.drop_column('fighter_profiles', 'fight_name')
    op.drop_column('fighter_profiles', 'last_name')
    op.drop_column('fighter_profiles', 'first_name')
    # ### end Alembic commands ###
