"""split fighter records into per-sport table, add bio

Revision ID: e2f7f89b360f
Revises: ec98ba46b167
Create Date: 2026-08-08 19:07:39.710861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2f7f89b360f'
down_revision: Union[str, Sequence[str], None] = 'ec98ba46b167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighter_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_profile_id', sa.Integer(), nullable=False),
    sa.Column('sport', postgresql.ENUM('boxing', 'mma', 'bjj', name='sport', create_type=False), nullable=False),
    sa.Column('gym', sa.String(length=200), nullable=True),
    sa.Column('status', postgresql.ENUM('pro', 'amateur', name='fighter_status', create_type=False), nullable=False),
    sa.Column('belt', sa.Enum('white', 'blue', 'purple', 'brown', 'black', name='belt_color'), nullable=True),
    sa.Column('amateur_wins', sa.Integer(), nullable=False),
    sa.Column('amateur_losses', sa.Integer(), nullable=False),
    sa.Column('amateur_draws', sa.Integer(), nullable=False),
    sa.Column('pro_wins', sa.Integer(), nullable=False),
    sa.Column('pro_losses', sa.Integer(), nullable=False),
    sa.Column('pro_draws', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fighter_profile_id'], ['fighter_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fighter_profile_id', 'sport', name='uq_fighter_sport')
    )
    # Carry each fighter's existing single sport/gym/record into their first
    # fighter_sports row before the source columns are dropped.
    op.execute("""
        INSERT INTO fighter_sports
            (fighter_profile_id, sport, gym, status, amateur_wins, amateur_losses, amateur_draws,
             pro_wins, pro_losses, pro_draws)
        SELECT id, sport, gym, status, amateur_wins, amateur_losses, amateur_draws,
               pro_wins, pro_losses, pro_draws
        FROM fighter_profiles
    """)

    op.add_column('fighter_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.drop_column('fighter_profiles', 'pro_wins')
    op.drop_column('fighter_profiles', 'amateur_draws')
    op.drop_column('fighter_profiles', 'pro_draws')
    op.drop_column('fighter_profiles', 'gym')
    op.drop_column('fighter_profiles', 'amateur_wins')
    op.drop_column('fighter_profiles', 'status')
    op.drop_column('fighter_profiles', 'sport')
    op.drop_column('fighter_profiles', 'amateur_losses')
    op.drop_column('fighter_profiles', 'pro_losses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fighter_profiles', sa.Column('pro_losses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('amateur_losses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('sport', postgresql.ENUM('boxing', 'mma', 'bjj', name='sport'), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('status', postgresql.ENUM('pro', 'amateur', name='fighter_status'), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('amateur_wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('gym', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('fighter_profiles', sa.Column('pro_draws', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('amateur_draws', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fighter_profiles', sa.Column('pro_wins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('fighter_profiles', 'bio')
    op.drop_table('fighter_sports')
    # ### end Alembic commands ###
