"""rework messages into conversations, add reactions and shared posts

Revision ID: eb9d81e9f443
Revises: e2f7f89b360f
Create Date: 2026-08-08 20:03:26.923759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb9d81e9f443'
down_revision: Union[str, Sequence[str], None] = 'e2f7f89b360f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_participant')
    )
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_reaction')
    )
    # conversation_id starts nullable so existing rows don't immediately
    # violate NOT NULL; backfilled below, then tightened.
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('shared_post_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'body',
               existing_type=sa.TEXT(),
               nullable=True)

    # One conversation per distinct pair of users who'd exchanged 1:1
    # messages under the old sender/recipient model.
    bind = op.get_bind()
    pairs = bind.execute(sa.text("""
        SELECT DISTINCT LEAST(sender_id, recipient_id) AS u1, GREATEST(sender_id, recipient_id) AS u2
        FROM messages
    """)).fetchall()

    for u1, u2 in pairs:
        conv_id = bind.execute(sa.text(
            "INSERT INTO conversations (is_group, created_at) VALUES (false, now()) RETURNING id"
        )).scalar()
        bind.execute(sa.text("""
            INSERT INTO conversation_participants (conversation_id, user_id, joined_at, last_read_at)
            VALUES (:c, :u1, now(), now()), (:c, :u2, now(), now())
        """), {"c": conv_id, "u1": u1, "u2": u2})
        bind.execute(sa.text("""
            UPDATE messages SET conversation_id = :c
            WHERE (sender_id = :u1 AND recipient_id = :u2) OR (sender_id = :u2 AND recipient_id = :u1)
        """), {"c": conv_id, "u1": u1, "u2": u2})

    op.alter_column('messages', 'conversation_id', nullable=False)
    op.drop_constraint(op.f('messages_recipient_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'posts', ['shared_post_id'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_recipient_id_fkey'), 'messages', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'shared_post_id')
    op.drop_column('messages', 'conversation_id')
    op.drop_table('message_reactions')
    op.drop_table('conversation_participants')
    op.drop_table('conversations')
    # ### end Alembic commands ###
