"""add likes comments and reposts

Revision ID: ec98ba46b167
Revises: 5df0bc3c0b15
Create Date: 2026-08-07 14:24:01.989312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec98ba46b167'
down_revision: Union[str, Sequence[str], None] = '5df0bc3c0b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate can't detect new values on an existing Postgres enum type,
    # so this has to be added by hand. Safe to run inside this migration's
    # transaction since nothing in this revision inserts a 'repost' row.
    op.execute("ALTER TYPE post_type ADD VALUE IF NOT EXISTS 'repost'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like')
    )
    op.add_column('posts', sa.Column('repost_of_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['repost_of_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Note: Postgres doesn't support removing a value from an enum type, so
    # 'repost' stays in post_type even after downgrading the rest of this.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'repost_of_id')
    op.drop_table('post_likes')
    op.drop_table('post_comments')
    # ### end Alembic commands ###
